// <auto-generated />
using System;
using LearningTrainerShared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningTrainerShared.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260304120000_AddUserNoteToProgress")]
    partial class AddUserNoteToProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This is a stub designer file. The snapshot is maintained in ApiDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
